apiVersion: platform.example.com/v1alpha1
kind: ObservabilityStack
metadata:
  name: main-observability-stack
  namespace: default
spec:
  parameters:
    namespace: "monitoring"
    prometheusStack:
      enabled: true
      storageClass: "nfs-csi"
      storageSize: "50Gi"
      retention: "30d"
    loki:
      enabled: true
      storageClass: "nfs-csi"
      storageSize: "100Gi"
    grafana:
      adminPassword: "admin123"  # Change this in production
      domain: "grafana.your-domain.com"  # Adjust to your domain
