apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xobservabilitystacks.platform.example.com
spec:
  group: platform.example.com
  names:
    kind: XObservabilityStack
    plural: xobservabilitystacks
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  namespace:
                    type: string
                    description: "Namespace where observability stack will be deployed"
                    default: "monitoring"
                  prometheusStack:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: true
                      storageClass:
                        type: string
                        default: "nfs-csi"
                      storageSize:
                        type: string
                        default: "50Gi"
                      retention:
                        type: string
                        default: "30d"
                  loki:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: true
                      storageClass:
                        type: string
                        default: "nfs-csi"
                      storageSize:
                        type: string
                        default: "100Gi"
                  grafana:
                    type: object
                    properties:
                      adminPassword:
                        type: string
                        default: "admin"
                      domain:
                        type: string
                        default: "grafana.local"
                required:
                - namespace
            required:
            - parameters
          status:
            type: object
            properties:
              conditions:
                description: Conditions of the resource.
                items:
                  description: A Condition that may apply to a resource.
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the last time this condition transitioned from one status to another.
                      format: date-time
                      type: string
                    message:
                      description: A Message containing details about this condition's last transition from one status to another, if any.
                      type: string
                    reason:
                      description: A Reason for this condition's last transition from one status to another.
                      type: string
                    status:
                      description: Status of this condition; is it currently True, False, or Unknown?
                      type: string
                    type:
                      description: Type of this condition. At most one of each condition type may apply to a resource at any point in time.
                      type: string
                  required:
                  - lastTransitionTime
                  - reason
                  - status
                  - type
                  type: object
                type: array
    additionalPrinterColumns:
    - name: READY
      type: string
      jsonPath: ".status.conditions[?(@.type=='Ready')].status"
    - name: COMPOSITION
      type: string
      jsonPath: ".metadata.labels['crossplane\\.io/composition']"
    - name: AGE
      type: date
      jsonPath: ".metadata.creationTimestamp"
  claimNames:
    kind: ObservabilityStack
    plural: observabilitystacks
