apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: ingress-stack
  labels:
    provider: helm
    service: ingress
spec:
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: XIngressStack
  
  resources:
  - name: ingress-namespace
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: ingress-system
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.namespace
      toFieldPath: spec.forProvider.manifest.metadata.name

  - name: metallb-namespace
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: metallb-system

  - name: metallb
    base:
      apiVersion: helm.crossplane.io/v1beta1
      kind: Release
      spec:
        rollbackLimit: 3
        forProvider:
          namespace: metallb-system
          chart:
            name: metallb
            repository: https://metallb.github.io/metallb
            version: "0.13.12"
          values:
            speaker:
              enabled: true
            controller:
              enabled: true

  - name: metallb-ippool
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: metallb.io/v1beta1
            kind: IPAddressPool
            metadata:
              name: default-pool
              namespace: metallb-system
            spec:
              addresses:
              - 10.20.0.81-10.20.0.99
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.metallb.ipPool
      toFieldPath: spec.forProvider.manifest.spec.addresses[0]

  - name: metallb-l2advertisement
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: metallb.io/v1beta1
            kind: L2Advertisement
            metadata:
              name: default-l2advertisement
              namespace: metallb-system
            spec:
              ipAddressPools:
              - default-pool

  - name: nginx-ingress
    base:
      apiVersion: helm.crossplane.io/v1beta1
      kind: Release
      spec:
        rollbackLimit: 3
        forProvider:
          namespace: ingress-system
          chart:
            name: ingress-nginx
            repository: https://kubernetes.github.io/ingress-nginx
            version: "4.8.3"
          values:
            controller:
              service:
                type: LoadBalancer
                externalTrafficPolicy: Local
              metrics:
                enabled: true
                serviceMonitor:
                  enabled: true
              admissionWebhooks:
                enabled: true
              config:
                use-forwarded-headers: "true"
                compute-full-forwarded-for: "true"
                use-proxy-protocol: "false"
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.namespace
      toFieldPath: spec.forProvider.namespace
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.nginx.loadBalancerIP
      toFieldPath: spec.forProvider.values.controller.service.loadBalancerIP

  writeConnectionSecretsToNamespace: crossplane-system
