apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: metallb-ipaddresspool
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: in-cluster
  forProvider:
    manifest:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: homelab-pool
        namespace: metallb-system
      spec:
        addresses:
          - 10.20.0.81-10.20.0.99
