apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: metallb-l2advertisement
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  providerConfigRef:
    name: in-cluster
  forProvider:
    manifest:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: homelab-l2adv
        namespace: metallb-system
      spec:
        ipAddressPools:
          - homelab-pool
