apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-services
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: homelab
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/homelab-services
    repoURL: https://github.com/jamilshaikh07/homelab-gitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true