apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  sources:
    - repoURL: https://github.com/jamilshaikh07/homelab-gitops
      path: manifests/velero-namespace
      targetRevision: main
    - repoURL: https://vmware-tanzu.github.io/helm-charts
      chart: velero
      targetRevision: 11.1.1
      helm:
        values: |
          credentials:
            secretContents:
              cloud: |
                [default]
                aws_access_key_id=james
                aws_secret_access_key=Jamil@123

          configuration:
            backupStorageLocation:
              - name: minio
                provider: aws
                bucket: velero
                config:
                  region: minio
                  s3ForcePathStyle: true
                  s3Url: http://10.20.0.41:9000
                default: true
            defaultVolumesToFsBackup: true
          snapshotsEnabled: false
          deployNodeAgent: true

          initContainers:
            - name: velero-plugin-for-aws
              image: velero/velero-plugin-for-aws:v1.13.0
              volumeMounts:
                - mountPath: /target
                  name: plugins

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true