apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: 10.1.2
    helm:
      values: |
        credentials:
          secretContents:
            cloud: |
              [default]
              aws_access_key_id=admin
              aws_secret_access_key=Jamil@123

        configuration:
          backupStorageLocation:
            - name: minio
              provider: aws
              bucket: velero
              config:
                region: minio
                s3ForcePathStyle: true
                s3Url: http://10.20.0.163:9000
          volumeSnapshotLocation:
            - name: minio
              provider: aws
              config:
                region: minio

        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.10.1
            volumeMounts:
              - mountPath: /target
                name: plugins

        deployNodeAgent: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true